### PR TITLE
Link Yoti account update

### PR DESCRIPTION
**Pull request by rob-yoti**

### CODE REVIEW

**Comment by rob-yoti** [comment]
@xchangebit Can you squash and merge if happy?

**Comment by rob-yoti** [comment]
@xchangebit bump

**Comment by rob-yoti** [comment]
@simontong @xchangebit Bump

**Comment by zarembas** [comment]
@sidibos Could you please take a look at this branch? @rob-yoti left Yoti some time ago. Let's see if it's worth tidying this branch up or ditching it entirely

**Pull request closed without merging**
