### PR TITLE
Release 1.4.0: Merge development -> master

### PR DESCRIPTION
**Pull request by davidgrayston**
### Changed
- Widget now displays QR code in modal
- "Yoti Dashboard" is now referred to as "Yoti Hub"

### CODE REVIEW

**Review by echarrod — APPROVED** [review]
Ran both Docker (with latest release), and `wordpress-dev` image, checked that QR is present (old on latest release, modal on dev).

Currently says `Yoti Scenario ID is used to render the inline QR code` on the settings page, can we update this to be something like `Yoti Scenario ID is used to render the modal window containing the QR code, for the scenario specified in Yoti Hub.` Does that sound ok @KiranBali?

Also had that issue with the tab being copied from Dashboard, have raised with Joe and they'll fix, but if we could also trim whitespace/tabs in the plugin, that would be great (not necessary for this release)

**Comment by davidgrayston** [comment]
@echarrod opened #58 to correct QR documentation

**Review by emmas-yoti — APPROVED** [review]

**Comment by KiranBali** [comment]
hello,

is there anyway we can keep it the same as https://developers.yoti.com/yoti-app/web-integration#step-3-front-end-integration

**Comment by davidgrayston** [comment]
I'll update each plugin to use these descriptions:

 | ID | Description |
-- | --
Client SDK ID | Identifies your Yoti Hub application. This value can be found in the Hub, within your application section, in the keys tab.
Scenario ID | Identifies the attributes associated with your Yoti application. This value can be found on your application page in Yoti Hub.

I've dropped `(navigate to Scenarios tab)` as this could change at any point to a different form of navigation.

@KiranBali can you confirm this is correct?

**Comment by KiranBali** [comment]
﻿Perfect 😊

 

Kiran Bali

+44 (0)7514606474


Fountain House, 130 Fenchurch Street, London, EC3M 5DJ

https://www.yoti.com

**Comment by KiranBali** [comment]
perfect :)

**Pull request merged**
